---
title: "R Notebook - Data Visualization"
output: html_notebook
---

## Beschriftungsparameter und -funktionen


```{r}
plot (x <- 0:48/5, sin(x),
      main="Titel der Grafik",
      sub="Untertitel der Grafik",
      xlab="X-Achsen-Beschriftung",
      ylab="Y-Achsen-Beschriftung",
      cex.main=3, col.sub="blue")
```

## DIESELBE AUSGABE BEWIRKT AUCH ...

```{r}
plot (x <- 0:48/5, sin(x),
      xlab="", ylab="")
title (main="Titel der Grafik",
       sub="Untertitel der Grafik",
       xlab="X-Achsen-Beschriftung",
       ylab="Y-Achsen-Beschriftung",
       cex.main=3, col.sub="blue")
```
## Farben
### A Color Wheel
```{r}
require(graphics)
pie(rep(1, 6), col = rainbow(6))
```
### ------ Some palettes ------------
```{r}
demo.pal <- function(
  n, border = if (n<32) "light gray" else NA,
  main = paste("color palettes;  n=",n),
  ch.col = c("rainbow(n, start=.7, end=.1)", "heat.colors(n)",
             "terrain.colors(n)", "topo.colors(n)", "cm.colors(n)"))
{
  nt <- length(ch.col)
  i <- 1:n; j <- n / nt; d <- j/6; dy <- 2*d
  plot(i,i+d, type="n",yaxt="n",ylab="",main=main)
  for (k in 1:nt) {
    rect(i-.5, (k-1)*j+ dy, i+.4, k*j,
         col = eval(parse(text=ch.col[k])), border = border)
    text(2*j,k * j +dy/4, ch.col[k])
  }
}
n <- if(.Device == "postscript") 64 else 16
demo.pal(n)
```
## Punktweise Grafikattribute
```{r}
colors
layout (1:3); n=25
plot (rnorm(n),
      col="magenta",
      cex=1:n/3)
plot (rnorm(n),
      cex=3,
      pch=17,
      col=1+1:5)
plot (rnorm(n),
      cex=3,
      col="blue",
      pch=1:n)
```
## Farbräume und Farbpaletten
```{r}
layout (matrix (c(1,3,2,3),2,2))
attach (iris); K <- length(levels(Species))
pie (x=table (Species), labels=levels (Species), col=rainbow (K))
plot (x=Sepal.Length*Sepal.Width, y=Petal.Length*Petal.Width,
      col=rainbow(K)[Species], pch=19)
barplot (as.matrix (aggregate(iris[-5],iris[+5],mean)[-1]),
         col=rainbow(K))
```
## Darstellung von 2D-Wertverläufen
```{r}
layout(matrix(1:12,3,4,byrow=TRUE))
x <- seq (-3, +3, by=0.5)
y <- (x-2) * x * (x+2)

for (ty in unlist(
  strsplit(
    "plhsbocn","")))
  plot (x, y,
        main=sub
        ("@",ty,"type=’@’"),
        type=ty, lwd=3, cex=2,
        col="blue")

for (ty in unlist(
  strsplit(
    "plhs","")))
  plot (y, x,
        main=sub
        ("@",ty,"type=’@’"),
        type=ty, lwd=3, cex=2,
        col="magenta")

par(mfrow=c(1,3))
```
## Perspektivgrafik
```{r}
x <- dnorm (-10:+10/5)
persp (z=x%o%x, theta=30, phi=30, expand=0.5, col="lightblue", main="3D-Gaußglocke")
persp (z=volcano, theta=150, phi=30, expand=0.4, col="green", shade=0.75, box=F, border=NA, main="Vulcano green")
persp (z=volcano [1:nrow(volcano)%%3==0, 1:ncol(volcano)%%3==0], theta=150, phi=30, expand=0.4, box=FALSE, main="Vulcano grid")
```
## 3D Scatterplot
```{r}
layout(matrix(1:4,2,2,byrow=TRUE))
library("scatterplot3d", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2")
z <- seq(-10, +10, 0.1); scatterplot3d (x=cos(z), y=sin(z), z=z, pch=19, highlight.3d=TRUE)
scatterplot3d (iris[4:2], color=1+unclass(iris$Species))
scatterplot3d (iris[3:1], type="h", pch=" ", lwd=5, color=rep(rainbow(10),15))
rb <- rainbow (151); rb3 <- t (col2rgb (rb)); scatterplot3d (rb3, color=rb, box=FALSE, axis=F) -> geo
tp <- cm.colors (151); tp3 <- t (col2rgb (tp)); geo$points3d (tp3, pch="X", col=tp)
```
